/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controller.GerenteController;
import funcionarios.Atendente;
import funcionarios.Veterinario;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author arthu
 */
public class TelaGerente extends javax.swing.JFrame {
    
    GerenteController a = new GerenteController();
    /**
     * Creates new form TelaGerente
     */
    public TelaGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarAtendente = new javax.swing.JButton();
        btnAlterarAtendente = new javax.swing.JButton();
        btnCadastrarVet = new javax.swing.JButton();
        btnBuscarVet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCadastrarNomeAtendente = new javax.swing.JTextField();
        txtCadastrarTelefoneAtendente = new javax.swing.JTextField();
        txtCadastrarEmailAtendente = new javax.swing.JTextField();
        txtCadastrarEnderecoAtendente = new javax.swing.JTextField();
        txtCadastrarSalarioAtendente = new javax.swing.JTextField();
        txtCadastrarCpfAtendente = new javax.swing.JTextField();
        txtCadastrarNomeVet = new javax.swing.JTextField();
        txtCadastrarTelefoneVet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCadastrarEmailVet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCadastrarEnderecoVet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCadastrarSalarioVet = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCadastrarCpfVet = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtConfeaVet = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCadastrarIdadeAtendente = new javax.swing.JTextField();
        txtCadastrarIdadeVet = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnAlterarVeterinario = new javax.swing.JButton();
        btnBuscarAtendente = new javax.swing.JButton();
        txtSenhaAtendente = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        txtSenhaVet = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        btnExcluirAtendente = new javax.swing.JButton();
        btnExcluirVeterinario = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarAtendente.setText("Cadastrar Atendente");
        btnCadastrarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 417, -1, -1));

        btnAlterarAtendente.setText("Alterar Atendente");
        btnAlterarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 417, -1, -1));

        btnCadastrarVet.setText("Cadastrar Veterinario");
        btnCadastrarVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVetActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 417, 136, -1));

        btnBuscarVet.setText("Buscar Veterinario");
        btnBuscarVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVetActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 383, 136, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        jLabel2.setText("Telefone:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        jLabel3.setText("E-mail:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        jLabel5.setText("Salario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, -1, -1));

        jLabel6.setText("CPF:*");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, -1, -1));

        jLabel8.setText("Cadastrar Atendente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtCadastrarNomeAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarNomeAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarNomeAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 44, 205, -1));

        txtCadastrarTelefoneAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarTelefoneAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarTelefoneAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 82, 205, -1));

        txtCadastrarEmailAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarEmailAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarEmailAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 120, 205, -1));

        txtCadastrarEnderecoAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarEnderecoAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarEnderecoAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 158, 205, -1));

        txtCadastrarSalarioAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarSalarioAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarSalarioAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 196, 205, -1));

        txtCadastrarCpfAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarCpfAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarCpfAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 234, 205, -1));

        txtCadastrarNomeVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarNomeVetActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarNomeVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 44, 211, -1));

        txtCadastrarTelefoneVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarTelefoneVetActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarTelefoneVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 82, 211, -1));

        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 47, -1, -1));
        getContentPane().add(txtCadastrarEmailVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 120, 211, -1));

        jLabel9.setText("Telefone:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 85, -1, -1));
        getContentPane().add(txtCadastrarEnderecoVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 158, 211, -1));

        jLabel10.setText("E-mail:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 123, -1, -1));

        txtCadastrarSalarioVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarSalarioVetActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarSalarioVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 196, 213, -1));

        jLabel11.setText("Endereço:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 161, -1, -1));
        getContentPane().add(txtCadastrarCpfVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 213, -1));

        jLabel12.setText("Salario:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 199, -1, -1));

        jLabel13.setText("CPF:*");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        jLabel14.setText("Cadastrar Veterinario");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 11, -1, -1));

        jLabel15.setText("CONFEA:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));
        getContentPane().add(txtConfeaVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 213, -1));

        jLabel16.setText("Idade:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, -1, -1));

        txtCadastrarIdadeAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarIdadeAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarIdadeAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 272, 205, -1));

        txtCadastrarIdadeVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrarIdadeVetActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastrarIdadeVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 213, -1));

        jLabel17.setText("Idade:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        btnAlterarVeterinario.setText("Alterar Veterinario");
        btnAlterarVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVeterinarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 417, -1, -1));

        btnBuscarAtendente.setText("Buscar Atendente");
        btnBuscarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 383, 135, -1));
        getContentPane().add(txtSenhaAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 310, 205, -1));

        jLabel19.setText("Senha:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 313, -1, -1));
        getContentPane().add(txtSenhaVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 213, -1));

        jLabel20.setText("Senha:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        btnExcluirAtendente.setText("Excluir Atendente");
        btnExcluirAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 383, 119, -1));

        btnExcluirVeterinario.setText("Excluir Veterinario");
        btnExcluirVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirVeterinarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 383, 125, -1));

        jLabel18.setText("* Campos Obrigatorios");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 351, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dd30vdq-207dbf67-71f7-4aec-8e82-95230bee44e4.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 180, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtendenteActionPerformed
        
        double salario;
        if(txtCadastrarSalarioAtendente.getText().trim().isEmpty()){
            txtCadastrarSalarioAtendente.setText("0");
        }
        salario = Double.parseDouble(txtCadastrarSalarioAtendente.getText());
 
        int idade;
        if(txtCadastrarIdadeAtendente.getText().trim().isEmpty()){
            txtCadastrarIdadeAtendente.setText("0");
        }
        idade = Integer.parseInt(txtCadastrarIdadeAtendente.getText());
        
        if(!txtCadastrarCpfAtendente.getText().trim().isEmpty()){
            if(!a.addFuncionario(txtCadastrarNomeAtendente.getText(), txtCadastrarTelefoneAtendente.getText(), txtCadastrarEmailAtendente.getText(), txtCadastrarEnderecoAtendente.getText(), salario , txtCadastrarCpfAtendente.getText(), "Atendente", "null", idade, txtSenhaAtendente.getText())){
                JOptionPane.showMessageDialog(null, "Preencha os campos necessários :C", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Atendente Cadastrado(a) :D", null, WIDTH);
        }else JOptionPane.showMessageDialog(null, "Cpf invalido e(ou) dados não inseridos", null, WIDTH);
        txtCadastrarNomeAtendente.setText(null);
        txtCadastrarTelefoneAtendente.setText(null);
        txtCadastrarEmailAtendente.setText(null);
        txtCadastrarEnderecoAtendente.setText(null);
        txtCadastrarSalarioAtendente.setText(null);
        txtCadastrarCpfAtendente.setText(null);
        txtCadastrarIdadeAtendente.setText(null);
        txtSenhaAtendente.setText(null);
        
    }//GEN-LAST:event_btnCadastrarAtendenteActionPerformed

    private void btnCadastrarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVetActionPerformed
        
        double salario;
        if(txtCadastrarSalarioVet.getText().trim().isEmpty()){
            txtCadastrarSalarioVet.setText("0");
        }
        salario = Double.parseDouble(txtCadastrarSalarioVet.getText());
 
        int idade;
        if(txtCadastrarIdadeVet.getText().trim().isEmpty()){
            txtCadastrarIdadeVet.setText("0");
        }
        idade = Integer.parseInt(txtCadastrarIdadeVet.getText());
        
        if(!txtCadastrarCpfVet.getText().trim().isEmpty()){
            if(!a.addFuncionario(txtCadastrarNomeVet.getText(), txtCadastrarTelefoneVet.getText(), txtCadastrarEmailVet.getText(), txtCadastrarEnderecoVet.getText(), salario , txtCadastrarCpfVet.getText(), "Veterinario", txtConfeaVet.getText(), idade, txtSenhaVet.getText())){
                JOptionPane.showMessageDialog(null, "Preencha os campos necessários :C", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Veterinario(a) Cadastrado(a) :D", null, WIDTH);
            
        }else JOptionPane.showMessageDialog(null, "Cpf invalido e(ou) dados não inseridos", null, WIDTH);     
        txtCadastrarNomeVet.setText(null);
        txtCadastrarTelefoneVet.setText(null);
        txtCadastrarEmailVet.setText(null);
        txtCadastrarEnderecoVet.setText(null);
        txtCadastrarSalarioVet.setText(null);
        txtCadastrarCpfVet.setText(null);
        txtCadastrarIdadeVet.setText(null);
        txtConfeaVet.setText(null);
        txtSenhaVet.setText(null);
        
    }//GEN-LAST:event_btnCadastrarVetActionPerformed

    private void txtCadastrarNomeAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarNomeAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarNomeAtendenteActionPerformed

    private void txtCadastrarTelefoneAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarTelefoneAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarTelefoneAtendenteActionPerformed

    private void txtCadastrarSalarioAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarSalarioAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarSalarioAtendenteActionPerformed

    private void txtCadastrarNomeVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarNomeVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarNomeVetActionPerformed

    private void txtCadastrarTelefoneVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarTelefoneVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarTelefoneVetActionPerformed

    private void txtCadastrarSalarioVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarSalarioVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarSalarioVetActionPerformed

    private void txtCadastrarEmailAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarEmailAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarEmailAtendenteActionPerformed

    private void txtCadastrarEnderecoAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarEnderecoAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarEnderecoAtendenteActionPerformed

    private void txtCadastrarCpfAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarCpfAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarCpfAtendenteActionPerformed

    private void btnAlterarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarAtendenteActionPerformed
        
        double salario;
        if(txtCadastrarSalarioAtendente.getText().trim().isEmpty()){
            txtCadastrarSalarioAtendente.setText("0");
        }
        salario = Double.parseDouble(txtCadastrarSalarioAtendente.getText());
 
        int idade;
        if(txtCadastrarIdadeAtendente.getText().trim().isEmpty()){
            txtCadastrarIdadeAtendente.setText("0");
        }
        idade = Integer.parseInt(txtCadastrarIdadeAtendente.getText());
        
        if(!a.attInfo(txtCadastrarNomeAtendente.getText(), txtCadastrarTelefoneAtendente.getText(), txtCadastrarEmailAtendente.getText(), txtCadastrarEnderecoAtendente.getText(), salario, txtCadastrarCpfAtendente.getText(), idade, "atendente", "")){
           JOptionPane.showMessageDialog(null, "Preencha os campos necessários :C", null, WIDTH);
        }else JOptionPane.showMessageDialog(null, "Dados alterados  :D", null, WIDTH);
        txtCadastrarNomeAtendente.setText(null);
        txtCadastrarTelefoneAtendente.setText(null);
        txtCadastrarEmailAtendente.setText(null);
        txtCadastrarEnderecoAtendente.setText(null);
        txtCadastrarSalarioAtendente.setText(null);
        txtCadastrarCpfAtendente.setText(null);
        txtCadastrarIdadeAtendente.setText(null);
    }//GEN-LAST:event_btnAlterarAtendenteActionPerformed
                                                  

    private void txtCadastrarIdadeVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarIdadeVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarIdadeVetActionPerformed

    private void txtCadastrarIdadeAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarIdadeAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrarIdadeAtendenteActionPerformed

    private void btnAlterarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVeterinarioActionPerformed
        
        double salario;
        if(txtCadastrarSalarioVet.getText().trim().isEmpty()){
            txtCadastrarSalarioVet.setText("0");
        }
        salario = Double.parseDouble(txtCadastrarSalarioVet.getText());
 
        int idade;
        if(txtCadastrarIdadeVet.getText().trim().isEmpty()){
            txtCadastrarIdadeVet.setText("0");
        }
        idade = Integer.parseInt(txtCadastrarIdadeVet.getText());
        
        if(!a.attInfo(txtCadastrarNomeVet.getText(), txtCadastrarTelefoneVet.getText(), txtCadastrarEmailVet.getText(), txtCadastrarEnderecoVet.getText(), salario, txtCadastrarCpfVet.getText(), idade, "veterinario", txtConfeaVet.getText())){
            JOptionPane.showMessageDialog(null, "Preencha os campos necessários :C", null, WIDTH);
        }else JOptionPane.showMessageDialog(null, "Dados alterados  :D", null, WIDTH);
        txtCadastrarNomeVet.setText(null);
        txtCadastrarTelefoneVet.setText(null);
        txtCadastrarEmailVet.setText(null);
        txtCadastrarEnderecoVet.setText(null);
        txtCadastrarSalarioVet.setText(null);
        txtCadastrarCpfVet.setText(null);
        txtCadastrarIdadeVet.setText(null);
        txtConfeaVet.setText(null);
    }//GEN-LAST:event_btnAlterarVeterinarioActionPerformed

    private void btnBuscarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAtendenteActionPerformed
        
        if(!txtCadastrarCpfAtendente.getText().trim().isEmpty()){
            
            Atendente atendente = new Atendente();
            atendente = a.buscarAtendente(txtCadastrarCpfAtendente.getText());
            String salario = String.valueOf(atendente.getSalario());
            
            
            if(!atendente.equals(null)){
               TelaPesquisarFuncionario tela = new TelaPesquisarFuncionario();
               tela.preencherDados(atendente.getNome(), atendente.getTelefone(), salario, atendente.getEmail(), atendente.getEndereco(), atendente.getCpf(), atendente.getCargo(), null);
               tela.setVisible(true);
               txtCadastrarCpfAtendente.setText(null);
               
            }
        }else  JOptionPane.showMessageDialog(null, "Preencha o Cpf >:[", null, WIDTH);
        
        
    }//GEN-LAST:event_btnBuscarAtendenteActionPerformed

    private void btnExcluirAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAtendenteActionPerformed
        
        int op = 1;
        
        if(! a.removerFuncionario(txtCadastrarCpfAtendente.getText(), op)){
            JOptionPane.showMessageDialog(null, "Preencha os campos necessários :C", null, WIDTH);
        }else JOptionPane.showMessageDialog(null, "Atendente removido(a) ;-;", null, WIDTH);
        
        txtCadastrarCpfAtendente.setText(null);
        
    }//GEN-LAST:event_btnExcluirAtendenteActionPerformed

    private void btnExcluirVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirVeterinarioActionPerformed
        
        int op = 0;
        
        if(!a.removerFuncionario(txtCadastrarCpfVet.getText(), op)){
            JOptionPane.showMessageDialog(null, "Preencha os campos necessários :C", null, WIDTH);
        }else JOptionPane.showMessageDialog(null, "Veterinario(a) removido(a) ;-;", null, WIDTH);
        
        txtCadastrarCpfVet.setText(null);
    }//GEN-LAST:event_btnExcluirVeterinarioActionPerformed

    private void btnBuscarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVetActionPerformed
        
        if(!txtCadastrarCpfVet.getText().trim().isEmpty()){
            
            Veterinario vet = new Veterinario();
            vet = a.buscarVeterinario(txtCadastrarCpfVet.getText());
            String salario = String.valueOf(vet.getSalario());
            
            
            if(!vet.equals(null)){
               TelaPesquisarFuncionario tela = new TelaPesquisarFuncionario();
               tela.preencherDados(vet.getNome(), vet.getTelefone(), salario, vet.getEmail(), vet.getEndereco(), vet.getCpf(), vet.getCargo(), vet.getConfea());
               tela.setVisible(true);
               txtCadastrarCpfVet.setText(null);
               
            }
        }else  JOptionPane.showMessageDialog(null, "Preencha o Cpf >:[", null, WIDTH);
        
    }//GEN-LAST:event_btnBuscarVetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarAtendente;
    private javax.swing.JButton btnAlterarVeterinario;
    private javax.swing.JButton btnBuscarAtendente;
    private javax.swing.JButton btnBuscarVet;
    private javax.swing.JButton btnCadastrarAtendente;
    private javax.swing.JButton btnCadastrarVet;
    private javax.swing.JButton btnExcluirAtendente;
    private javax.swing.JButton btnExcluirVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCadastrarCpfAtendente;
    private javax.swing.JTextField txtCadastrarCpfVet;
    private javax.swing.JTextField txtCadastrarEmailAtendente;
    private javax.swing.JTextField txtCadastrarEmailVet;
    private javax.swing.JTextField txtCadastrarEnderecoAtendente;
    private javax.swing.JTextField txtCadastrarEnderecoVet;
    private javax.swing.JTextField txtCadastrarIdadeAtendente;
    private javax.swing.JTextField txtCadastrarIdadeVet;
    private javax.swing.JTextField txtCadastrarNomeAtendente;
    private javax.swing.JTextField txtCadastrarNomeVet;
    private javax.swing.JTextField txtCadastrarSalarioAtendente;
    private javax.swing.JTextField txtCadastrarSalarioVet;
    private javax.swing.JTextField txtCadastrarTelefoneAtendente;
    private javax.swing.JTextField txtCadastrarTelefoneVet;
    private javax.swing.JTextField txtConfeaVet;
    private javax.swing.JPasswordField txtSenhaAtendente;
    private javax.swing.JPasswordField txtSenhaVet;
    // End of variables declaration//GEN-END:variables
}
