/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import controller.AtendenteController;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author arthu
 */
public class TelaCadastrarConsulta extends javax.swing.JFrame {

   AtendenteController a = new AtendenteController();
    public TelaCadastrarConsulta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarConsulta = new javax.swing.JButton();
        btnCancelarCadastroConsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeClienteConsulta = new javax.swing.JTextField();
        txtEspecieAnimalConsulta = new javax.swing.JTextField();
        txtDataConsulta = new javax.swing.JTextField();
        txtHoraConsulta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIdConsulta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Consulta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarConsulta.setText("Cadastrar");
        btnCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        btnCancelarCadastroConsulta.setText("Cancelar");
        btnCancelarCadastroConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadastroConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarCadastroConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel1.setText("Nome do Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setText("Especie do animal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Data da consulta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("Horario da consulta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtNomeClienteConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeClienteConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 230, -1));

        txtEspecieAnimalConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieAnimalConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEspecieAnimalConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, -1));

        txtDataConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 230, -1));

        txtHoraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoraConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Gamakichi_%28Render%29.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 160, 190));
        getContentPane().add(txtIdConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 230, -1));

        jLabel7.setText("Id da consulta:*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        jLabel8.setText("* Campos Obrigatorios");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void fechar(){
        this.dispose();
    }
    
    private void txtEspecieAnimalConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieAnimalConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieAnimalConsultaActionPerformed

    private void txtHoraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraConsultaActionPerformed

    private void btnCancelarCadastroConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadastroConsultaActionPerformed
        fechar();
    }//GEN-LAST:event_btnCancelarCadastroConsultaActionPerformed

    private void btnCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConsultaActionPerformed
        if(!a.cadastrarConsulta(txtNomeClienteConsulta.getText(), txtEspecieAnimalConsulta.getText(), txtHoraConsulta.getText(), txtDataConsulta.getText(), txtIdConsulta.getText())){
         JOptionPane.showMessageDialog(null, "Preencha os campos necessários :[", null, WIDTH);
        }else JOptionPane.showMessageDialog(null, "Consulta Cadastrada :)", null, WIDTH);
        txtNomeClienteConsulta.setText(null);
        txtEspecieAnimalConsulta.setText(null);
        txtHoraConsulta.setText(null);
        txtDataConsulta.setText(null);
        txtIdConsulta.setText(null);
    }//GEN-LAST:event_btnCadastrarConsultaActionPerformed

    private void txtNomeClienteConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteConsultaActionPerformed

    private void txtDataConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarConsulta;
    private javax.swing.JButton btnCancelarCadastroConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDataConsulta;
    private javax.swing.JTextField txtEspecieAnimalConsulta;
    private javax.swing.JTextField txtHoraConsulta;
    private javax.swing.JTextField txtIdConsulta;
    private javax.swing.JTextField txtNomeClienteConsulta;
    // End of variables declaration//GEN-END:variables

}
