/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author arthu
 */
public class TelaPesquisarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisarFuncionario
     */
    public TelaPesquisarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCpfPesquisarFuncionario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtConfeaPesquisarFuncionario = new javax.swing.JTextField();
        txtNomePesquisarFuncuncionario = new javax.swing.JTextField();
        txtTelefonePesquisarFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailPesquisarFuncionario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEnderecoPesquisarFuncionario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSalarioPesquisarFuncionario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCancelarPesquisaFuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCargoPesquisarFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCpfPesquisarFuncionario.setEditable(false);
        txtCpfPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfPesquisarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfPesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 201, 211, -1));

        jLabel12.setText("Salario:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, -1, -1));

        jLabel13.setText("CPF:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, -1));

        jLabel15.setText("CONFEA:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtConfeaPesquisarFuncionario.setEditable(false);
        txtConfeaPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfeaPesquisarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtConfeaPesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 277, 211, -1));

        txtNomePesquisarFuncuncionario.setEditable(false);
        txtNomePesquisarFuncuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePesquisarFuncuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomePesquisarFuncuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 11, 211, -1));

        txtTelefonePesquisarFuncionario.setEditable(false);
        txtTelefonePesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonePesquisarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefonePesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 49, 211, -1));

        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        txtEmailPesquisarFuncionario.setEditable(false);
        txtEmailPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailPesquisarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailPesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 87, 211, -1));

        jLabel9.setText("Telefone:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        txtEnderecoPesquisarFuncionario.setEditable(false);
        txtEnderecoPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoPesquisarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtEnderecoPesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 125, 211, -1));

        jLabel10.setText("E-mail:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtSalarioPesquisarFuncionario.setEditable(false);
        txtSalarioPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioPesquisarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalarioPesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 163, 211, -1));

        jLabel11.setText("Endereço:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));

        btnCancelarPesquisaFuncionario.setText("Voltar");
        btnCancelarPesquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPesquisaFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPesquisaFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 315, -1, -1));

        jLabel1.setText("Cargo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, -1, -1));

        txtCargoPesquisarFuncionario.setEditable(false);
        txtCargoPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoPesquisarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCargoPesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 239, 211, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dcra83f-8e58f65d-4de2-483b-a2d2-d51a5d8e6064.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 270, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void fechar(){
        this.dispose();
    }
    
    public void preencherDados(String nomeFuncionario, String telefoneFuncionario, String salarioFuncionario, String emailFuncionario, String enderecoFuncionario, String cpfFuncionario, String cargoFuncionario, String confeaVeterinario){
        
        txtNomePesquisarFuncuncionario.setText(nomeFuncionario);
        txtTelefonePesquisarFuncionario.setText(telefoneFuncionario);
        txtSalarioPesquisarFuncionario.setText(salarioFuncionario);
        txtEmailPesquisarFuncionario.setText(emailFuncionario);
        txtEnderecoPesquisarFuncionario.setText(enderecoFuncionario);
        txtCpfPesquisarFuncionario.setText(cpfFuncionario);
        txtCargoPesquisarFuncionario.setText(cargoFuncionario);
        txtConfeaPesquisarFuncionario.setText(confeaVeterinario);
        
        
    }
    
    
    private void txtNomePesquisarFuncuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePesquisarFuncuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePesquisarFuncuncionarioActionPerformed

    private void txtTelefonePesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonePesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonePesquisarFuncionarioActionPerformed

    private void txtSalarioPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioPesquisarFuncionarioActionPerformed

    private void btnCancelarPesquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPesquisaFuncionarioActionPerformed
        fechar();
    }//GEN-LAST:event_btnCancelarPesquisaFuncionarioActionPerformed

    private void txtEmailPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailPesquisarFuncionarioActionPerformed

    private void txtEnderecoPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoPesquisarFuncionarioActionPerformed

    private void txtCpfPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfPesquisarFuncionarioActionPerformed

    private void txtCargoPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoPesquisarFuncionarioActionPerformed

    private void txtConfeaPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfeaPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfeaPesquisarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPesquisaFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCargoPesquisarFuncionario;
    private javax.swing.JTextField txtConfeaPesquisarFuncionario;
    private javax.swing.JTextField txtCpfPesquisarFuncionario;
    private javax.swing.JTextField txtEmailPesquisarFuncionario;
    private javax.swing.JTextField txtEnderecoPesquisarFuncionario;
    private javax.swing.JTextField txtNomePesquisarFuncuncionario;
    private javax.swing.JTextField txtSalarioPesquisarFuncionario;
    private javax.swing.JTextField txtTelefonePesquisarFuncionario;
    // End of variables declaration//GEN-END:variables
}
