/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import clientes.Cliente;
import controller.AtendenteController;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;
import java.io.IOException;
/**
 *
 * @author arthu
 */
public class TelaAtendente extends javax.swing.JFrame {

    public AtendenteController a = new AtendenteController();
    
    /**
     * Creates new form TelaAtendente
     */
    public TelaAtendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarCliente = new javax.swing.JButton();
        btnAlterarInfoCliente = new javax.swing.JButton();
        btnRemoverCliente = new javax.swing.JButton();
        btnCadastrarConsulta = new javax.swing.JButton();
        btnPesquisarCliente = new javax.swing.JButton();
        txtCpfCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTelefoneCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atendente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarCliente.setText("Cadastrar");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 233, -1, -1));

        btnAlterarInfoCliente.setText("Alterar");
        btnAlterarInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarInfoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarInfoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 233, -1, -1));

        btnRemoverCliente.setText("Remover");
        btnRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoverCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 233, -1, -1));

        btnCadastrarConsulta.setText("Cadastrar consulta");
        btnCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 274, -1, -1));

        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 58, 111, -1));

        txtCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 80, 274, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 39, -1, 23));

        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 40, 274, -1));

        jLabel2.setText("CPF:*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 83, -1, -1));

        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 147, -1, -1));

        txtTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 144, 274, -1));

        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 178, -1, -1));

        txtEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 175, 274, -1));

        jLabel5.setText("* Campos Obrigatorios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 308, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 30, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dazjdhu-96292558-12a4-49ea-bf87-ef22d4574bcf.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 270, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarInfoClienteActionPerformed
        if(txtEmailCliente.getText().trim().isEmpty() && txtTelefoneCliente.getText().trim().isEmpty()){//alterar o nome
            if(!a.attNome(txtCpfCliente.getText(), txtNomeCliente.getText())){
                JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Dado Alterado com sucesso :D", null, WIDTH);
        }else
        if(txtNomeCliente.getText().trim().isEmpty() && txtEmailCliente.getText().trim().isEmpty()){//alterar o telefone
            if(!a.attTelefone(txtCpfCliente.getText(), txtTelefoneCliente.getText())){
              JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Dado Alterado com sucesso :D", null, WIDTH);
        }else
        if(txtNomeCliente.getText().trim().isEmpty() && txtTelefoneCliente.getText().trim().isEmpty()){//alterar o email
            if(!a.attEmail(txtCpfCliente.getText(), txtEmailCliente.getText())){
                JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Dado Alterado com sucesso :D", null, WIDTH);
        }else
        if(txtEmailCliente.getText().trim().isEmpty()){//alterar nome e telefone
            if(a.attNome(txtCpfCliente.getText(), txtNomeCliente.getText()) && a.attTelefone(txtCpfCliente.getText(), txtTelefoneCliente.getText())){
                JOptionPane.showMessageDialog(null, "Dado Alterado com sucesso :D", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
        }else
        if(txtTelefoneCliente.getText().trim().isEmpty()){//alterar o nome e email
            if(a.attNome(txtCpfCliente.getText(), txtNomeCliente.getText()) && a.attEmail(txtCpfCliente.getText(), txtEmailCliente.getText())){
                JOptionPane.showMessageDialog(null, "Dado Alterado com sucesso :D", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
        }else
        if(txtNomeCliente.getText().trim().isEmpty()){//alterar o email e telefone
            if(a.attEmail(txtCpfCliente.getText(), txtEmailCliente.getText()) && a.attTelefone(txtCpfCliente.getText(), txtTelefoneCliente.getText())){
             JOptionPane.showMessageDialog(null, "Dado Alterado com sucesso :D", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
        }else { //alterar tuso
            if(a.attNome(txtCpfCliente.getText(), txtNomeCliente.getText()) && a.attTelefone(txtCpfCliente.getText(), txtTelefoneCliente.getText()) && a.attEmail(txtCpfCliente.getText(), txtEmailCliente.getText())){
              JOptionPane.showMessageDialog(null, "Dado Alterado com sucesso :D", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
        };
        
        txtNomeCliente.setText(null);
        txtCpfCliente.setText(null);
        txtTelefoneCliente.setText(null);
        txtEmailCliente.setText(null);
        
    }//GEN-LAST:event_btnAlterarInfoClienteActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        
        if(!txtCpfCliente.getText().trim().isEmpty()){
            
            Cliente cliente = new Cliente();
            cliente = a.buscarCliente(txtCpfCliente.getText());
            if(!cliente.equals(null)){
               TelaPesquisarCliente tela = new TelaPesquisarCliente();
               tela.preencherDados(cliente.getNome(), cliente.getCpf(), cliente.getTelefone(), cliente.getEmail());
               tela.setVisible(true);
               txtCpfCliente.setText(null);
               
            }
        }else  JOptionPane.showMessageDialog(null, "Preencha o Cpf >:[", null, WIDTH);
        
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void txtCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfClienteActionPerformed
       
        
    
    }//GEN-LAST:event_txtCpfClienteActionPerformed

    private void txtEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailClienteActionPerformed
        
        
        
    }//GEN-LAST:event_txtEmailClienteActionPerformed

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed

       
        
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void txtTelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneClienteActionPerformed
        
    }//GEN-LAST:event_txtTelefoneClienteActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        
        if(!txtCpfCliente.getText().trim().isEmpty()){
            if(!a.cadastrarCliente(txtNomeCliente.getText(), txtCpfCliente.getText(), txtTelefoneCliente.getText(), txtEmailCliente.getText())){
                JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Cliente Cadastrado :)", null, WIDTH);  
        }else JOptionPane.showMessageDialog(null, "Cpf invalido e(ou) dados não inseridos", null, WIDTH);
        
        txtNomeCliente.setText(null);
        txtCpfCliente.setText(null);
        txtTelefoneCliente.setText(null);
        txtEmailCliente.setText(null);
        
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverClienteActionPerformed
        if(txtCpfCliente.getText().trim().isEmpty()){
            if(!a.removerCliente(1, txtNomeCliente.getText())){
                JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Cliente removido >.<", null, WIDTH);
        }
            
        if(txtNomeCliente.getText().trim().isEmpty()){
            if(!a.removerCliente(2, txtCpfCliente.getText())){
              JOptionPane.showMessageDialog(null, "Algo deu errado :[", null, WIDTH);
            }else JOptionPane.showMessageDialog(null, "Cliente removido >.<", null, WIDTH);
        }
            
        
        txtNomeCliente.setText(null);
        txtCpfCliente.setText(null);
        txtTelefoneCliente.setText(null);
        txtEmailCliente.setText(null);
    }//GEN-LAST:event_btnRemoverClienteActionPerformed

    private void btnCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConsultaActionPerformed
        
        TelaCadastrarConsulta tela = new TelaCadastrarConsulta();
        tela.setVisible(true);
        
    }//GEN-LAST:event_btnCadastrarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarInfoCliente;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarConsulta;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnRemoverCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
