/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controller.VeterinarioController;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author arthu
 */
public class TelaVeterinario extends javax.swing.JFrame {
    
    VeterinarioController a = new VeterinarioController();
    /**
     * Creates new form TelaVeterinario
     */
    public TelaVeterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        btnCadastrarExame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeClienteExame = new javax.swing.JTextField();
        txtEspecieAnimalExame = new javax.swing.JTextField();
        txtNomeExame = new javax.swing.JTextField();
        txtValorExame = new javax.swing.JTextField();
        txtDataExame = new javax.swing.JTextField();
        txtHoraExame = new javax.swing.JTextField();
        btnVerConsultas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdExame = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnVerExames = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarExame.setText("Cadastrar Exame");
        btnCadastrarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarExameActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel1.setText("Nome do Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setText("Especie do animal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("Nome do exame:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setText("Valor do exame:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Data:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel6.setText("Hora:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtNomeClienteExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteExameActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeClienteExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 253, -1));

        txtEspecieAnimalExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieAnimalExameActionPerformed(evt);
            }
        });
        getContentPane().add(txtEspecieAnimalExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 253, -1));

        txtNomeExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeExameActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 254, -1));

        txtValorExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorExameActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 254, -1));

        txtDataExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataExameActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 254, -1));

        txtHoraExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraExameActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoraExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 254, -1));

        btnVerConsultas.setText("Ver Consultas");
        btnVerConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 115, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/b678f255f2b8492bf53fc21cf4eecb63.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 590, 800));
        getContentPane().add(txtIdExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 250, -1));

        jLabel9.setText("Id do exame:*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, -1));

        jLabel10.setText("* Campos Obrigatorios");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 20));

        btnVerExames.setText("Ver Exames");
        btnVerExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerExamesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerExames, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarExameActionPerformed
        
        double valor;
        if(txtValorExame.getText().trim().isEmpty()){
            txtValorExame.setText("0");
        }
        valor = Double.parseDouble(txtValorExame.getText());
        
        if(!txtNomeClienteExame.getText().trim().isEmpty() && !txtEspecieAnimalExame.getText().trim().isEmpty() && !txtNomeExame.getText().trim().isEmpty() && !txtValorExame.getText().trim().isEmpty() && !txtDataExame.getText().trim().isEmpty() && !txtHoraExame.getText().trim().isEmpty()){
            if(a.cadastrarExame(txtNomeClienteExame.getText(), txtEspecieAnimalExame.getText(), txtNomeExame.getText(), valor, txtDataExame.getText(), txtHoraExame.getText(), txtIdExame.getText())){
                JOptionPane.showMessageDialog(null, "Exame Cadastrado :D", null, WIDTH);
                txtValorExame.setText(null);
                txtNomeClienteExame.setText(null);
                txtDataExame.setText(null);
                txtEspecieAnimalExame.setText(null);
                txtHoraExame.setText(null);
                txtNomeExame.setText(null);
            }else JOptionPane.showMessageDialog(null, "Algo deu errado .D.", null, WIDTH);
        }else JOptionPane.showMessageDialog(null, "Dados do Exame em Branco", null, WIDTH);
        txtValorExame.setText(null);
        
    }//GEN-LAST:event_btnCadastrarExameActionPerformed

    private void txtNomeClienteExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteExameActionPerformed

    private void txtEspecieAnimalExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieAnimalExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieAnimalExameActionPerformed

    private void txtNomeExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeExameActionPerformed

    private void txtValorExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorExameActionPerformed

    private void txtDataExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataExameActionPerformed

    private void txtHoraExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraExameActionPerformed

    private void btnVerConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerConsultasActionPerformed
       new TelaBuscarConsulta().setVisible(true);
    }//GEN-LAST:event_btnVerConsultasActionPerformed

    private void btnVerExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerExamesActionPerformed
        new TelaBuscarExame().setVisible(true);
    }//GEN-LAST:event_btnVerExamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarExame;
    private javax.swing.JButton btnVerConsultas;
    private javax.swing.JButton btnVerExames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtDataExame;
    private javax.swing.JTextField txtEspecieAnimalExame;
    private javax.swing.JTextField txtHoraExame;
    private javax.swing.JTextField txtIdExame;
    private javax.swing.JTextField txtNomeClienteExame;
    private javax.swing.JTextField txtNomeExame;
    private javax.swing.JTextField txtValorExame;
    // End of variables declaration//GEN-END:variables
}
