/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author arthu
 */
public class TelaPesquisarCliente extends javax.swing.JFrame {
    
   
    /**
     * Creates new form TelaPesquisarCliente
     */
    public TelaPesquisarCliente() {
        
        initComponents();
    }
    
    
    public void fechar(){
        this.dispose();
    }
    
     public void preencherDados(String nomeCliente, String cpfCliente, String telefoneCliente, String emailCliente){
        
        
        txtNomeBuscaCliente.setText(nomeCliente);
        txtTelefoneBuscaCliente.setText(telefoneCliente);
        txtEmailBuscaCliente.setText(emailCliente);
        txtCpfBuscaCliente.setText(cpfCliente);
        
        
        
    }
    
    /*
    public void preencherDados(String nomeCliente, String cpfCliente, String telefoneCliente, String emailCliente){
        
        
        txtNomeBuscaCliente.setText(nomeCliente);
        txtTelefoneBuscaCliente.setText(telefoneCliente);
        txtEmailBuscaCliente.setText(emailCliente);
        txtCpfBuscaCliente.setText(cpfCliente);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        txtNomeBuscaCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTelefoneBuscaCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailBuscaCliente = new javax.swing.JTextField();
        txtCpfBuscaCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarPesquisa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisar Cliente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomeBuscaCliente.setEditable(false);
        txtNomeBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeBuscaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeBuscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 12, 274, -1));

        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, -1, -1));

        txtTelefoneBuscaCliente.setEditable(false);
        txtTelefoneBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneBuscaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefoneBuscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 90, 274, -1));

        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, -1, -1));

        txtEmailBuscaCliente.setEditable(false);
        txtEmailBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailBuscaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailBuscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 128, 274, -1));

        txtCpfBuscaCliente.setEditable(false);
        txtCpfBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfBuscaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfBuscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 52, 274, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 23));

        btnCancelarPesquisa.setText("Voltar");
        btnCancelarPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 167, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/autigone-fukasaku-20975.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 220, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeBuscaClienteActionPerformed
        //txtNomeBuscaCliente.setText(nomeCliente);
    }//GEN-LAST:event_txtNomeBuscaClienteActionPerformed

    private void txtTelefoneBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneBuscaClienteActionPerformed
       // txtTelefoneBuscaCliente.setText(telefoneCliente);
    }//GEN-LAST:event_txtTelefoneBuscaClienteActionPerformed

    private void txtEmailBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailBuscaClienteActionPerformed
        //txtEmailBuscaCliente.setText(emailCliente);
    }//GEN-LAST:event_txtEmailBuscaClienteActionPerformed

    private void txtCpfBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfBuscaClienteActionPerformed
       // txtCpfBuscaCliente.setText(cpfCliente);
    }//GEN-LAST:event_txtCpfBuscaClienteActionPerformed

    private void btnCancelarPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPesquisaActionPerformed
        fechar();
    }//GEN-LAST:event_btnCancelarPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisarCliente().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCpfBuscaCliente;
    private javax.swing.JTextField txtEmailBuscaCliente;
    private javax.swing.JTextField txtNomeBuscaCliente;
    private javax.swing.JTextField txtTelefoneBuscaCliente;
    // End of variables declaration//GEN-END:variables
}
